### ISSUE TITLE
install TVDemon without installing youtube-dl or yt-dlp which is outdated in Ubuntu LTS or Linux LTS others

### ISSUE THREAD

**Issue by candrapersada** [DYefremov/TVDemon#3]
Is there an option to install TVDemon without installing youtube-dl or yt-dlp from the Ubuntu LTS repository so you can use the latest version of yt-dlp?

**Comment by DYefremov** [comment]
youtube-dl has nothing to do with TVDemon.  It's installed as the recommended package (if I remember correctly) when installing **MPV**. Once installed, you can remove youtube-dl manually.
`sudo apt remove youtube-dl`
I always do this in Linux Mint.
