### ISSUE TITLE
Volume level with scroll mouse

### ISSUE THREAD

**Issue by skaox** [DYefremov/TVDemon#4]
Hi,
would it be possible to manage volume level with scroll mouse ?
This is the most important thing missing (for me).
Thank you in advance

**Comment by DYefremov** [comment]
Hi, 
I'm planning some changes to the GUI and will try to take this moment in account. As a last resort, I'll add a control panel.

**Comment by DYefremov** [comment]
So far I've added a simple implementation (without indication display).

**Comment by skaox** [comment]
I replaced the 3 files changed in /usr/lib/tvdemon

Wonderful a big THANK YOU !

**Comment by DYefremov** [comment]
> I'll add a control panel.

Added media bar with volume control. I think this topic can be closed.

**Comment by skaox** [comment]
Sure THANK YOU
