### ISSUE TITLE
run TVDemon on MSYS2

### ISSUE THREAD

**Issue by candrapersada** [DYefremov/TVDemon#5]
why is there no clear information on how to run `TVDemon` on `MSYS2` in the README?

**Comment by DYefremov** [comment]
Will be available later. Perhaps, it will added the ability to build as a standalone package also.

**Comment by DYefremov** [comment]
Added [quick guide](https://github.com/DYefremov/TVDemon/blob/main/build/win/BUILD.md).

**Comment by candrapersada** [comment]
```
Traceback (most recent call last):
  File "C:/msys64/home/Candra/TVDemon/usr/lib/tvdemon/run.py", line 23, in <module>
    from app.main import run
  File "C:/msys64/home/Candra/TVDemon/usr/lib/tvdemon/app/main.py", line 34, in <module>
    from imdb import IMDb
ModuleNotFoundError: No module named 'imdb'
```

**Comment by DYefremov** [comment]
Yes, I forgot one step. You need to install [IMDbPY](https://pypi.org/project/IMDbPY/).
In the  **mingw64** shell: 
`pip3 install imdbpy`

**Comment by candrapersada** [comment]
```
The syntax of the command is incorrect.
'charmap' codec can't decode byte 0x90 in position 29835: character maps to <undefined>
Traceback (most recent call last):
  File "C:/msys64/home/Candra/TVDemon/usr/lib/tvdemon/app/main.py", line 1442, in reload
    if self.manager.check_playlist(provider):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:/msys64/home/Candra/TVDemon/usr/lib/tvdemon/app/common.py", line 300, in check_playlist
    content = file.read()
              ^^^^^^^^^^^
  File "C:/msys64/mingw64/lib/python3.11/encodings/cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 29835: character maps to <undefined>
Couldn't parse provider info:  Free-TV:::url:::https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8:::::::::'
Loading providers...
Free-TV: Getting playlist...
Free-TV: Checking playlist...

```

**Comment by DYefremov** [comment]
"Old" problem  -> UTF-8 encoding on Windows.:) What is your **system locale**? Apparently you have **cp1252** .
What output for `locale` command in the mingw64 shell?
At me looks so:
```
$ locale
LANG=
LC_CTYPE="ru_RU.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```

**Comment by candrapersada** [comment]
```
Couldn't parse provider info:  Free-TV:::url:::https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8:::::::::'
```

**Comment by DYefremov** [comment]
> `Couldn't parse provider info: Free-TV:::url:::https://raw.githubusercontent.com/Free-TV/IPTV/master/playlist.m3u8:::::::::'`

I saw it.

What output for `locale` command in the **mingw64 shell**?

**Comment by candrapersada** [comment]
```
Candra@WIN-FQDKQ385NBO MINGW64 ~
$ locale
LANG=
LC_CTYPE="id_ID.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=

```
![image](https://github.com/DYefremov/TVDemon/assets/36833664/fad32530-ae5d-4584-bad1-5d9695b457cb)

**Comment by DYefremov** [comment]
OK. Interesting... Needs to experiment on free time.  Does [this build](https://github.com/DYefremov/TVDemon/releases/download/1.2.0-b1/TVDemon-1.2.0-Beta-win64.zip) work at you?

**Comment by candrapersada** [comment]
> Does [this build](https://github.com/DYefremov/TVDemon/releases/download/1.2.0-b1/TVDemon-1.2.0-Beta-win64.zip) work at you?

no
![image](https://github.com/DYefremov/TVDemon/assets/36833664/91145107-3d18-4a93-a674-fded950d481c)

**Comment by DYefremov** [comment]
Hm, at me works.
![build](https://github.com/DYefremov/TVDemon/assets/7511379/8bc7be15-0e52-41d0-b253-cb31318b7a4a)


 OK. I'll experiment as possible.

**Comment by candrapersada** [comment]
```
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file C:\Users\Candra\AppData\Local\Microsoft\Windows\INetCache\tvdemon\providers already exists.
Error occurred while processing: C:\Users\Candra\AppData\Local\Microsoft\Windows\INetCache\tvdemon\providers.

[process exited with code 1 (0x00000001)]
You can now close this terminal with Ctrl+D, or press Enter to restart.
```

**Comment by DYefremov** [comment]
For an experiment, try local *m3u files also, e.g from [here](https://github.com/iptv-org/iptv).

**Comment by DYefremov** [comment]
Added forced playlist reading in UTF-8. I hope it helps.

**Comment by candrapersada** [comment]
> For an experiment, try local *m3u files also, e.g from [here](https://github.com/iptv-org/iptv).

not working

> Added forced playlist reading in UTF-8. I hope it helps.

working but
```
  File "C:/msys64/home/Candra/TVDemon/usr/lib/tvdemon/app/madia.py", line 151, in get_mpv
    from . import mpv
  File "C:/msys64/home/Candra/TVDemon/usr/lib/tvdemon/app/mpv.py", line 35, in <module>
    raise OSError('Cannot find mpv-1.dll or mpv-2.dll in your system %PATH%. One way to deal with this is to ship '
OSError: Cannot find mpv-1.dll or mpv-2.dll in your system %PATH%. One way to deal with this is to ship the dll with your script and put the directory your script is in into %PATH% before "import mpv": os.environ["PATH"] = os.path.dirname(__file__) + os.pathsep + os.environ["PATH"] If mpv-1.dll is located elsewhere, you can add that path to os.environ["PATH"].

```

**Comment by DYefremov** [comment]
Have you installed _libmpv_ as described [here](https://github.com/DYefremov/TVDemon/blob/main/build/win/BUILD.md)?

**Comment by DYefremov** [comment]
[Changed](https://github.com/DYefremov/TVDemon/commit/7259ba4588ec7d533c2108a82d32f5d3e255769b) the name for library search. Try again.

**Comment by candrapersada** [comment]
yes working
